{
    'name': "Open HRMS Employees Modify",
    'version': '15.0.1.0.0',
    'summary': """Open HRMS Employees Modify""",
    'description': """Open HRMS Employees Modify """,
    'live_test_url': 'https://youtu.be/6VN13PG5g_w',
    'category': 'Human Resource',
    'author': 'Cybrosys Techno solutions,Open HRMS',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': "https://www.openhrms.com",
    'depends': ['base', 'hr', 'oh_employee_creation_from_user'],
    'data': [
                'views/hr_employee_modify_views.xml',
                'views/technology_views.xml',
                'security/ir.model.access.csv',
                'views/frameworks_views.xml',
                'views/tools_views.xml',
                'views/database_views.xml',
                'views/deployment_tools_views.xml',
                'views/version_control_views.xml',
                'views/previous_compny_views.xml',
                'views/inherit_modify_views.xml',
                'views/server_views.xml',
                'views/develop_ops_tool_view.xml',
                'views/opeting_system_views.xml',
                'views/monitoring_tool_views.xml',
                'views/project_management.xml',
                'views/other_tools_technologies_views.xml',
                'views/education_views.xml',
                'views/bank_modify_view.xml',
            ],
    # 'demo': ['data/regularization_data.xml'],
    # 'images': ['static/description/banner.png'],
    'license': "AGPL-3",
    'installable': True,
    'application': True,
}
